on:
  push:
    tags:
      - 'v*'

name: Create Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release-${{ github.event.release.tag_name }}.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release-${{ github.event.release.tag_name }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}